companies:
  - name: Mega
    url: http://mega.co.nz
    twitter: megaPrivacy
    
  - name: Catayst IT
    url: http://catalyst.net.nz
    twitter: catalystnz

  - name: Vend
    twitter: vendhq

  - name: Xero
    twitter: xero

  - name: NZX
    url: http://nzx.com
    twitter: NZXGroup

  - name: DataCom
    url: http://datacom.co.nz/
    twitter: Datacom
  
  - name: Silverstripe
    url: http://silverstripe.com/
    twitter: silverstripe

  - name: Affinity
    url: https://www.affinity.net.nz/
    twitter: affinitynz

  - name: I want my name
    twitter: iwantmyname
    url: http://iwantmyname.co.nz

#  - name: EasyApps
#  - name: Whakatu Computer Services
#  - name: Nodero
#  - name: KOORB
#  - name: My Republic
#  - name: Zeald
#  - name: CactusLab

  - name: PowerShop
    url: http://www.powershop.co.nz/
    twitter: powershop

#  - name: Touchtech
#  - name: Uprise Digital
#  - name: Flightless
#  - name: Provoke
#  - name: Innovators
#  - name: Swaytech

  - name: Rabid
    twitter: rabidtech
    url: http://rabid.co.nz

  - name: The Bridge Street Collective
    url: http://www.bridgestreet.co.nz/
    twitter: bridge_st

#  - name: Moa Creative
#  - name: Spider Tracks
#  - name: Abletech
#  - name: Tumunu
#  - name: YouDo
#  - name: Pixel Fusion
#  - name: Hive News
  - name: Enspiral
    twitter: enspiral
    diversitydata: yes
    documentation: https://twitter.com/enspiral/status/489983678454697984
    img: enspiral.png

#  - name: Startup Law
#  - name: Mobile Mentor
